# Generated by Django 4.2.5 on 2025-01-30 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Task Name')),
                ('done', models.BooleanField(default=False, verbose_name='Completed')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='Date Completed')),
            ],
        ),
    ]
