# Generated by Django 4.2.5 on 2025-02-05 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="date_completed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date Of Completion"
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date Of Task Created"
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="name",
            field=models.CharField(max_length=1000, verbose_name="Name Of Task"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todostasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
